---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
    keypair: ansible
    instance_type: t2.micro
    security_group: full_access
    image: ami-0bcc094591f354be2
    region: us-east-1

  tasks:
    - name: Add instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-8f7f0ec2
        assign_public_ip: yes
      register: ec2

    - name: Add instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        ansible_ssh_user: "ubuntu"
        groupname: web
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

- name: Install nginx
  hosts: web
  become: yes

  tasks:
    - name: nginx is present
      apt:
        name: nginx
        state: present

    - name: index.html is present
      copy:
        src: index.html
        dest: /var/www/html
        mode: '0644'

    - name: nginx is started
      service:
        name: nginx
        state: started
